/* 
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,

  the first 10 terms will be:
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
? find the sum of the even-valued terms
 */

#include <iostream>

using namespace std;

/* returns sum of even-valued fibonacci numbers till given number */
int fib_sum(int max){
    int total = 0, fib_new = 2, fib_prev_1 = 1, fib_prev_2;

    while (fib_new <= max) {    // iteration till given max
        if (fib_new % 2 == 0){  // even fibonacci number
            total += fib_new;
        }

        fib_prev_2 = fib_prev_1;
        fib_prev_1 = fib_new;
        fib_new = fib_prev_1 + fib_prev_2;
    }

    return total;
}


int main(){
    cout << fib_sum(4000000);

    return 0;
}