""" 
  Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
*   Triangle	 	    𝑇ₙ = 𝑛(𝑛+1)/2	 	        1, 3, 6, 10, 15, ...
*   Pentagonal	 	    𝑃ₙ = 𝑛(3𝑛−1)/2	 	    1, 5, 12, 22, 35, ...
*   Hexagonal	 	    𝐻ₙ = 𝑛(2𝑛−1)	 	        1, 6, 15, 28, 45, ...

  It can be verified that 𝑇₂₈₅ = 𝑃₁₆₅ = 𝐻₁₄₃ = 40755.

? Find the next triangle number that is also pentagonal and hexagonal.
"""

