/* 
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,

  the first 10 terms will be:
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
? find the sum of the even-valued terms
*/

function fibEvenSum(nums_under) {
  let sum = 0;
  let fib_prev_2 = 1;
  let fib_prev_1 = 1;
  let Fnew;

  for (Fnew = 2; Fnew < nums_under; Fnew = fib_prev_2 + fib_prev_1) {
    fib_prev_2 = fib_prev_1;
    fib_prev_1 = Fnew;
    if (Fnew % 2 === 0) {
      sum += Fnew;
    }
  }

  return sum;
}

if (typeof require !== "undefined" && require.main === module) {
  console.log(fibEvenSum(4_000_000));
}
